version: '3'

services:
  node:
    restart: always
    build: .
    container_name: poke_api
    ports:
      - 8080:3000
      - 9229:9229

    depends_on:
      - mongo

  mongo:
    image: mongo
    container_name: poke_db
    restart: always
    ports:
      - 27017:27017
    volumes:
      - mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password

volumes:
 mongodb: